### ISSUE TITLE
Table of contents disappeared

### ISSUE THREAD

**Issue by kruzda** [rackerlabs/docs-cloud-load-balancers#134] opened 2016-06-01 09:11 UTC
It should normally be on the left side of the screen right after the submit an issue link.
See https://developer.rackspace.com/docs/cloud-servers/v2/developer-guide/#document-index for an example

**Comment by cyrichardson** [comment] 2016-06-01 13:09
@kruzda Thanks for reporting this.
@meker12 Do you have any ideas about why this would happen and how to fix it?

**Comment by cyrichardson** [comment] 2016-06-01 14:04
@smashwilson Is this perhaps something similar to what you just found with the rpc vm docs?

**Comment by smashwilson** [comment] 2016-06-01 14:08
When a table of contents disappears entirely, it's likely caused by the use of an incorrect template.

Have you changed the Sphinx builder used for this repository recently?

**Comment by cyrichardson** [comment] 2016-06-01 14:11
@smashwilson Not that I am aware of. There have been no recent changes. PR was on May 2.

**Comment by smashwilson** [comment] 2016-06-01 14:12
Oh, I see. The template for this repository was changed in rackerlabs/nexus-control#471, but the content is still using [the `deconst-single` builder](https://github.com/rackerlabs/docs-cloud-load-balancers/blob/master/api-docs/cloud-load-balancers-v1/conf.py#L55-L57).

You can either change the builder to `deconst-serial` or revert the template mapping back to `docs-singlepage.html`.

**Comment by smashwilson** [comment] 2016-06-01 14:13
Actually, I have a better idea. I bet I can change the `user-guide.html` template to work with _either_ builder. That'll make it much easier to transition between builders on these repositories.

**Comment by cyrichardson** [comment] 2016-06-01 14:17
Thank you @smashwilson !

**Comment by cyrichardson** [comment] 2016-06-01 14:23
@smashwilson I believe that @meker12 is currently doing some testing with the load balancers doc for the TOC change to show chunks of text instead of the whole long page. That is probably why the change was made in nexus control. @meker12 can confirm.

**Comment by meker12** [comment] 2016-06-01 14:35
@smashwilson Kelly and I are refactoring the API doc architecture to use the singlehtml template, so that's why we changed it.

**Comment by smashwilson** [comment] 2016-06-01 14:40
You mean refactoring to use the serial builder and `user-guide.html` template, right?

rackerlabs/nexus-control#476 should ease the transition. The TOC is [appearing again now](https://developer.rackspace.com/docs/cloud-load-balancers/v1/developer-guide/).

**Comment by cyrichardson** [comment] 2016-06-01 14:50
Thank you @smashwilson and @meker12! Closing this issue now.

**Comment by cyrichardson** [comment] 2016-06-01 14:50
@kruzda The issue your reported is fixed. Thanks again for reporting it.

**Closed by cyrichardson** 2016-06-01 14:50 UTC
